### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by kcchrist** [juliensalinas/torrengo#16]
Not certain why my install fails. 

Throws this error. Is this on my end or yours? How can I help determine that?

go/src/github.com/juliensalinas/torrengo/core/core.go:176:17: assignment mismatch: 2 variables but network.SetCookie(cookie.Name, cookie.Value).WithExpires(&expiry).WithDomain(cookie.Domain).WithPath(cookie.Path).WithHTTPOnly(cookie.HttpOnly).WithSecure(cookie.Secure).Do returns 1 values

**Comment by juliensalinas** [comment]
Well spotted @kcchrist I actually have the same problem but hadn't noticed it because I was using an older version.
Let me push a fix in a moment

**Comment by juliensalinas** [comment]
Thanks a lot @kcchrist . It was due to a breaking change in the ChromeDP lib: https://github.com/chromedp/cdproto/commit/2cc87dae3ee38df0ab811aeb3450793309d27bfa
I just fixed the code accordingly 👍🏻

**Comment by kcchrist** [comment]
Thank you!

**Comment by kcchrist** [comment]
Thank you. Still getting the same error on install attempt go get at 176:17, however.

**Comment by juliensalinas** [comment]
It must be because you did not update the lib. You should run `go get -u`. The `-u` option is important.
Let me know if it's still not working.
